---
- name: Instalar Docker
  hosts: servers
  become: yes
  vars:
    CTOP_VERSION: "0.7.3"
    DOCKER_COMPOSE_VERSION: "1.25.1"
    DOCKER_PACKAGES:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    USER: ubuntu

  tasks:
  - name: Actualizar paquetes apt
    apt:
      update_cache: "yes"
      force_apt_get: "yes"

  - name: Instalar paquetes para Docker
    apt:
      name: "{{ DOCKER_PACKAGES }}"
      state: present
      force_apt_get: "yes"

  - name: Agrega Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Salva el release de Ubuntu en una variable
    shell: lsb_release -cs
    register: ubuntu_version

  - name: Agrega el repositorio Docker
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
      state: present

  - name: Actualiza los paquetes apt
    apt:
      update_cache: "yes"
      force_apt_get: "yes"

  - name: Instala Docker
    apt:
      name: "docker-ce"
      state: present
      force_apt_get: "yes"

  - name: Prueba Docker con el contenedor hello world
    shell: "docker run hello-world"
    register: hello_world_output

  - name: Muestra la salida del contenedor hello world
    debug:
      msg: "Container Output: {{hello_world_output.stdout}}"

  - name: Create el grupo docker
    group:
      name: "docker"
      state: present

  - name: Agrega el usuario ubuntu al grupo docker
    user:
      name: "ubuntu"
      groups: "docker"
      append: "yes"

  - name: Instala Docker Compose
    get_url:
      url: https://github.com/docker/compose/releases/download/{{ DOCKER_COMPOSE_VERSION }}/docker-compose-Linux-x86_64
      dest: "/usr/local/bin/docker-compose"
      mode: 0755

  - name: Instala Ctop
    get_url:
      url: https://github.com/bcicen/ctop/releases/download/v{{ CTOP_VERSION }}/ctop-{{ CTOP_VERSION }}-linux-amd64
      dest: "/usr/local/bin/ctop"
      mode: 0755

  - name: Instala Python
    apt:
      name: python3
      state: present

  - name: Instala pip3
    apt:
      name: python3-pip
      state: present

  - name: Instala módulo Docker para Python
    pip:
      name: docker

  - name: Reinicia la VM para que los cambios surgan efecto
    shell: "Reinicia"
    async: 1
    poll: 0


